import { useEffect, useState } from "react";
type Api = <T>(path: string, init?: RequestInit) => Promise<T>;
type Source = { report_id: string; original_url: string; fragments: { locator: string; original_text: string; ocr_status: string }[] };
export function ReportTranscription({ projectId, jobId, api, onSubmitted }: { projectId: string; jobId: string; api: Api; onSubmitted: (value: Record<string, unknown>) => void }) {
  const [source, setSource] = useState<Source | null>(null), [pages, setPages] = useState<Record<string, string>>({}), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; api<{ report_id: string }>(`/jobs/${jobId}`).then(j => api<Source>(`/projects/${projectId}/reports/${j.report_id}`)).then(s => { if (active) { setSource(s); setPages(Object.fromEntries(s.fragments.filter(f => f.ocr_status === "NEEDS_TRANSCRIPTION").map(f => [f.locator.split(":")[1], ""]))); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [jobId, projectId, api]);
  const submit = async () => { if (!source) return; setBusy(true); setError(""); try { onSubmitted(await api<Record<string, unknown>>(`/projects/${projectId}/reports/${source.report_id}/transcriptions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pages }) })); } catch (e) { setError(e instanceof Error ? e.message : "Transcription failed"); } finally { setBusy(false); } };
  return <section className="report-transcription" aria-label="Page transcription"><h3>Transcribe original pages</h3>{source ? <><a href={source.original_url} target="_blank" rel="noreferrer">Open immutable original PDF</a><iframe className="original-page-view" title="Original PDF pages" src={source.original_url} />{source.fragments.map(f => <div key={f.locator}><h4>{f.locator}</h4><p className="muted">Original extracted text: {f.original_text || "No readable text"}</p>{f.ocr_status === "NEEDS_TRANSCRIPTION" && <label>Reviewed transcription · {f.locator}<textarea rows={5} disabled={busy} value={pages[f.locator.split(":")[1]] || ""} onChange={e => setPages(previous => ({ ...previous, [f.locator.split(":")[1]]: e.target.value }))} /></label>}</div>)}<button type="button" className="primary" disabled={busy || !Object.keys(pages).length || Object.values(pages).some(p => !p.trim())} onClick={() => void submit()}>{busy ? "Submitting…" : "Attach transcription and create review job"}</button></> : <p role="status">Loading original pages…</p>}{error && <p role="alert" className="form-error">{error}</p>}</section>;
}
