import { useEffect, useState } from "react";
export type ReportSpec = { sheet: string; header_row: number; columns: Record<string, number>; context: Record<string, string>; date_format: string | null };
type Preview = { sheets: { name: string; rows: { cell: string; value: string }[][] }[]; mappings: { id: string; template: string; revision: number; spec: ReportSpec; header_signature: string }[]; row_errors?: { locator: string; errors: string[] }[]; valid_rows?: number; header_signature?: string };
type Api = <T>(path: string, init?: RequestInit) => Promise<T>;
const fields = ["work_description", "report_date", "area", "asset_tag", "discipline", "event_kind", "actual_start", "actual_finish", "quantity", "unit", "quantity_kind"];
export function ReportMapping({ file, projectId, api, onConfirmed }: { file: File; projectId: string; api: Api; onConfirmed: (id: string | null) => void }) {
  const [preview, setPreview] = useState<Preview | null>(null), [spec, setSpec] = useState<ReportSpec>({ sheet: "", header_row: 1, columns: {}, context: {}, date_format: null });
  const [template, setTemplate] = useState("Discipline report"), [error, setError] = useState(""), [busy, setBusy] = useState(false), [confirmed, setConfirmed] = useState(false);
  const base = `/projects/${projectId}/reports`;
  useEffect(() => { let active = true; setBusy(true); const body = new FormData(); body.append("file", file); api<Preview>(base + "/preview", { method: "POST", body }).then(value => { if (active) { setPreview(value); setSpec({ sheet: value.sheets[0]?.name || "", header_row: 1, columns: {}, context: {}, date_format: null }); } }).catch(reason => { if (active) setError(reason.message); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [file, base, api]);
  const change = (next: ReportSpec) => { setSpec(next); setConfirmed(false); onConfirmed(null); };
  const validate = async (next: ReportSpec) => { const body = new FormData(); body.append("file", file); body.append("mapping", JSON.stringify(next)); const result = await api<Preview>(base + "/preview", { method: "POST", body }); setPreview(result); if (result.row_errors?.length) throw new Error("Correct the listed source rows before submitting."); if (!result.valid_rows) throw new Error("No report rows found."); return result; };
  const confirm = async (savedId?: string, next = spec) => { setBusy(true); setError(""); try { const result = await validate(next); let id = savedId; if (savedId && preview?.mappings.find(m => m.id === savedId)?.header_signature !== result.header_signature) throw new Error("Headers changed. Confirm a new mapping."); if (!id) { const saved = await api<{ id: string }>(base + "/mappings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ template, header_signature: result.header_signature, spec: next }) }); id = saved.id; } onConfirmed(id); setConfirmed(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Mapping failed"); } finally { setBusy(false); } };
  const sheet = preview?.sheets.find(s => s.name === spec.sheet), headers = sheet?.rows[spec.header_row - 1] || [];
  return <section aria-label="Report column mapping"><h3>Map report columns</h3>{busy && <p role="status">Checking workbook…</p>}{preview && <><label>Saved template<select disabled={busy} value="" onChange={e => { const m = preview.mappings.find(x => x.id === e.target.value); if (m) { change(m.spec); setTemplate(m.template); void confirm(m.id, m.spec); } }}><option value="">Choose a confirmed template</option>{preview.mappings.map(m => <option key={m.id} value={m.id}>{m.template} · revision {m.revision}</option>)}</select></label><label>Sheet<select value={spec.sheet} disabled={busy} onChange={e => change({ ...spec, sheet: e.target.value, columns: {} })}>{preview.sheets.map(s => <option key={s.name}>{s.name}</option>)}</select></label><label>Header row (preview shows first 20)<input type="number" min={1} max={20} value={spec.header_row} disabled={busy} onChange={e => change({ ...spec, header_row: Number(e.target.value), columns: {} })} /></label><div className="report-preview"><table><caption>Original cells · {spec.sheet}</caption><tbody>{sheet?.rows.slice(0, 6).map((r, i) => <tr key={i}>{r.map(c => <td key={c.cell}><small>{c.cell}</small> {c.value}</td>)}</tr>)}</tbody></table></div>{fields.map(field => <label key={field}>{field.replaceAll("_", " ")}<select disabled={busy} value={spec.columns[field] || ""} onChange={e => { const columns = { ...spec.columns }; if (e.target.value) columns[field] = Number(e.target.value); else delete columns[field]; change({ ...spec, columns }); }}><option value="">Unmapped</option>{headers.map((h, i) => <option key={i} value={i + 1}>{h.cell} · {h.value || "(empty)"}</option>)}</select></label>)}<label>File discipline<input disabled={busy} value={spec.context.discipline || ""} onChange={e => change({ ...spec, context: { ...spec.context, discipline: e.target.value } })} /></label><label>File area<input disabled={busy} value={spec.context.area || ""} onChange={e => change({ ...spec, context: { ...spec.context, area: e.target.value } })} /></label><label>Date format<select disabled={busy} value={spec.date_format || ""} onChange={e => change({ ...spec, date_format: e.target.value || null })}><option value="">ISO / native Excel dates</option><option value="%d/%m/%Y">Day/month/year</option><option value="%m/%d/%Y">Month/day/year</option></select></label><label>Template name<input disabled={busy} value={template} onChange={e => setTemplate(e.target.value)} /></label><button type="button" className="secondary" disabled={busy || !template.trim() || !spec.columns.work_description} onClick={() => void confirm()}>Confirm and save mapping</button>{confirmed && <p role="status">Mapping confirmed. Ready to submit.</p>}{preview.row_errors?.map(r => <p className="form-error" key={r.locator}>{r.locator}: {r.errors.join("; ")}</p>)}</>}{error && <p role="alert" className="form-error">{error}</p>}</section>;
}
