"""persistence foundation"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_persistence_foundation"; down_revision = None; branch_labels = None; depends_on = None
UUID = postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table("users", sa.Column("id", UUID, primary_key=True), sa.Column("username", sa.String(120), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(20), nullable=False), sa.Column("is_active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("projects", sa.Column("id", UUID, primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("active_schedule_version_id", UUID), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("project_memberships", sa.Column("project_id", UUID, sa.ForeignKey("projects.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("schedule_versions", sa.Column("id", UUID, primary_key=True), sa.Column("project_id", UUID, sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer, nullable=False), sa.Column("source_file_id", UUID), sa.Column("content_sha256", sa.String(64), nullable=False), sa.Column("state", sa.String(24), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("project_id", "version_number"), sa.UniqueConstraint("project_id", "content_sha256"))
    op.create_foreign_key("fk_project_active_schedule", "projects", "schedule_versions", ["active_schedule_version_id"], ["id"])
    op.create_table("activities", sa.Column("id", UUID, primary_key=True), sa.Column("schedule_version_id", UUID, sa.ForeignKey("schedule_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("external_id", sa.String(200), nullable=False), sa.Column("name", sa.String(500), nullable=False), sa.Column("wbs", sa.String(500), nullable=False), sa.Column("discipline", sa.String(40), nullable=False), sa.Column("work_type", sa.String(60), nullable=False), sa.Column("area", sa.String(200)), sa.Column("asset_tags", sa.Text), sa.Column("aliases", sa.Text), sa.Column("is_leaf", sa.Boolean, nullable=False), sa.Column("measurement_basis", sa.String(30), nullable=False), sa.Column("planned_quantity", sa.Numeric(18,4)), sa.Column("unit", sa.String(20)), sa.Column("baseline_date", sa.Date), sa.Column("baseline_quantity", sa.Numeric(18,4)), sa.Column("planned_start", sa.Date), sa.Column("planned_finish", sa.Date), sa.Column("actual_start", sa.Date), sa.Column("actual_finish", sa.Date), sa.UniqueConstraint("schedule_version_id", "external_id"))
    op.create_table("activity_states", sa.Column("activity_id", UUID, sa.ForeignKey("activities.id", ondelete="CASCADE"), primary_key=True), sa.Column("revision", sa.Integer, nullable=False), sa.Column("completed_quantity", sa.Numeric(18,4), nullable=False), sa.Column("physical_percent", sa.Numeric(8,4)), sa.Column("observed_status", sa.String(30), nullable=False), sa.Column("actual_start", sa.Date), sa.Column("actual_finish", sa.Date), sa.Column("last_observed_date", sa.Date))
    op.create_table("sessions", sa.Column("token_hash", sa.String(64), primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("csrf_hash", sa.String(64), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revoked_at", sa.DateTime(timezone=True)))
def downgrade():
    op.drop_table("sessions"); op.drop_table("activity_states"); op.drop_table("activities"); op.drop_constraint("fk_project_active_schedule", "projects", type_="foreignkey"); op.drop_table("schedule_versions"); op.drop_table("project_memberships"); op.drop_table("projects"); op.drop_table("users")
