from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0004_review"; down_revision="0003_jobs"; branch_labels=None; depends_on=None
U=postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table("observations",sa.Column("id",U,primary_key=True),sa.Column("job_id",U,sa.ForeignKey("jobs.id",ondelete="CASCADE"),nullable=False),sa.Column("fragment_id",U,sa.ForeignKey("fragments.id")),sa.Column("ordinal",sa.Integer,nullable=False),sa.Column("fields",sa.JSON,nullable=False),sa.Column("field_evidence",sa.JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("job_id","fragment_id","ordinal"))
    op.create_table("proposals",sa.Column("id",U,primary_key=True),sa.Column("observation_id",U,sa.ForeignKey("observations.id",ondelete="CASCADE"),nullable=False),sa.Column("revision",sa.Integer,nullable=False),sa.Column("project_id",U,sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("chosen_activity_id",U,sa.ForeignKey("activities.id")),sa.Column("candidates",sa.JSON,nullable=False),sa.Column("mapping_state",sa.String(24),nullable=False),sa.Column("match_strength",sa.String(24),nullable=False),sa.Column("review_state",sa.String(24),nullable=False),sa.Column("warnings",sa.JSON,nullable=False),sa.Column("proposed_effects",sa.JSON,nullable=False),sa.Column("base_activity_revision",sa.Integer),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("observation_id","revision"))
    op.create_table("progress_events",sa.Column("id",U,primary_key=True),sa.Column("activity_id",U,sa.ForeignKey("activities.id",ondelete="CASCADE"),nullable=False),sa.Column("observation_id",U,sa.ForeignKey("observations.id"),nullable=False),sa.Column("proposal_id",U,sa.ForeignKey("proposals.id"),nullable=False),sa.Column("proposal_revision",sa.Integer,nullable=False),sa.Column("approved_values",sa.JSON,nullable=False),sa.Column("effect_kind",sa.String(32),nullable=False),sa.Column("effective_date",sa.Date),sa.Column("reviewer_id",U,sa.ForeignKey("users.id"),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("supersedes_event_id",U,sa.ForeignKey("progress_events.id")),sa.Column("source_key",sa.String(255),unique=True))
    op.create_table("audit_events",sa.Column("id",U,primary_key=True),sa.Column("actor_id",U,sa.ForeignKey("users.id"),nullable=False),sa.Column("action",sa.String(64),nullable=False),sa.Column("target_type",sa.String(64),nullable=False),sa.Column("target_id",U,nullable=False),sa.Column("before",sa.JSON),sa.Column("after",sa.JSON),sa.Column("reason",sa.Text),sa.Column("request_id",sa.String(255)),sa.Column("timestamp",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("idempotency_keys",sa.Column("id",U,primary_key=True),sa.Column("actor_id",U,sa.ForeignKey("users.id"),nullable=False),sa.Column("endpoint",sa.String(120),nullable=False),sa.Column("key",sa.String(255),nullable=False),sa.Column("request_hash",sa.String(64),nullable=False),sa.Column("result_reference",sa.JSON),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("actor_id","endpoint","key"))
def downgrade():
    for t in ("idempotency_keys","audit_events","progress_events","proposals","observations"): op.drop_table(t)
